fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    webapp_config: git://github.com/hairmare/puppet-webapp-config.git
    apache: git@github.com:purplehazech/puppetlabs-apache.git
  symlinks:
    zabbix : "#{source_dir}"
